// <auto-generated />
namespace Transportsystem_GoogleMaps.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedPhoneNumberValidation3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedPhoneNumberValidation3));
        
        string IMigrationMetadata.Id
        {
            get { return "201705030922163_addedPhoneNumberValidation3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
